### ISSUE TITLE
glob and rglob broke with Python 3.8.3

### ISSUE THREAD

**Issue by impredicative** [liormizr/s3path#32]
This used to work fine with Python 3.8.2, but doesn't in 3.8.3. The [Python changelog](https://docs.python.org/3/whatsnew/changelog.html) does show relevant changes for `.glob` and `.scandir` for Python 3.8.3, one of which is https://bugs.python.org/issue39916. This Python issue also affects 3.7 and 3.9.

```python
>>> import sys
>>> sys.version
'3.8.3 (default, May 19 2020, 13:54:14) \n[Clang 10.0.0 ]'

>>> import s3path
>>> p = s3path.S3Path.from_uri('s3://noaa-gefs-pds')

>>> next(p.iterdir())
S3Path('/noaa-gefs-pds/gefs.20170101')

>>> next(p.glob('*'))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/removed/lib/python3.8/site-packages/s3path.py", line 502, in glob
    yield from super().glob(pattern)
  File "/removed/lib/python3.8/pathlib.py", line 1136, in glob
    for p in selector.select_from(self):
  File "/removed/lib/python3.8/pathlib.py", line 530, in _select_from
    with scandir(parent_path) as scandir_it:
AttributeError: __enter__

>>> next(p.rglob('*'))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/removed/lib/python3.8/site-packages/s3path.py", line 508, in rglob
    yield from super().rglob(pattern)
  File "/removed/lib/python3.8/pathlib.py", line 1148, in rglob
    for p in selector.select_from(self):
  File "/removed/lib/python3.8/pathlib.py", line 583, in _select_from
    for p in successor_select(starting_point, is_dir, exists, scandir):
  File "/removed/lib/python3.8/pathlib.py", line 530, in _select_from
    with scandir(parent_path) as scandir_it:
AttributeError: __enter__
```

Note that `glob` and `rglob` of course continue to work fine for `pathlib.Path`:
```python
>>> import pathlib

>>> next(pathlib.Path('/tmp').glob('*'))
PosixPath('/tmp/com.apple.launchd.6n6VKSqeWo')

>>> next(pathlib.Path('/tmp').rglob('*'))
PosixPath('/tmp/com.apple.launchd.6n6VKSqeWo')
```

The tricky point could be to support both Python 3.8.2 and 3.8.3.

**Comment by liormizr** [comment]
Hi @impredicative,
Thanks for the great catch! :-)

Deployed to PyPi and conda-forge, version: 0.1.101
